name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  PREFIX: ${GITHUB_WORKSPACE}/inst

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: >
          sudo apt-get update

          sudo apt-get install -y
          make gcc
          man texinfo texlive-binaries
          texlive-latex-base texlive-latex-recommended texlive-latex-extra
          texlive-bibtex-extra texlive-fonts-recommended

      - name: Build
        run: make

      - name: Install
        run: make install

      - name: Test
        run: make check

      - name: Clean
        run: make clean

      - name: Distribution
        run: TAR=tar make dist

  macos:
    name: macOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: brew install texinfo texlive

      - name: Build
        run: make

      - name: Install
        run: make install

      - name: Test
        run: make check

  windows-mingw:
    name: Windows
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    env:
      PLATFORM: -DMSDOS
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install:  >-
            make mingw-w64-x86_64-gcc
            man mingw-w64-x86_64-texinfo
            mingw-w64-x86_64-texlive-bin mingw-w64-x86_64-texlive-latex-recommended mingw-w64-x86_64-texlive-latex-extra
            mingw-w64-x86_64-texlive-bibtex-extra mingw-w64-x86_64-texlive-fonts-recommended mingw-w64-x86_64-texlive-plain-generic

      - name: Update PREFIX
        run: echo "PREFIX=$(cygpath -u $PREFIX)" >> $GITHUB_ENV

      - name: Build
        run: make

      - name: Install
        run: make install

      - name: Test
        run: make check
